name: Check Formatting with Prettier

on: [push, pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Prettier Check
        uses: actionsx/prettier@v3
        with:
          args: --check .
